---
openstackclient_image: quay.io/tripleowallaby/openstack-tripleoclient:current-tripleo
osp_release_defaults:
  release: wallaby
  container_tag: current-tripleo
  base_image_url: https://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-GenericCloud-9-latest.x86_64.qcow2
  #TODO: which ceph images tag to use for upstream train?
  #ceph_tag: 5-12
  #ceph_image: daemon
ephemeral_heat:
  heat_api_image: quay.io/tripleowallaby/openstack-heat-api:current-tripleo
  heat_engine_image: quay.io/tripleowallaby/openstack-heat-engine:current-tripleo
  mariadb_image: quay.io/tripleowallaby/openstack-mariadb:current-tripleo
  rabbit_image: quay.io/tripleowallaby/openstack-rabbitmq:current-tripleo
