---
roles:
  - name: chrony
    src: https://github.com/openstack/ansible-role-chrony.git
    version: 1.0.1

collections:
  - name: ansible.posix
  - name: containers.podman
  - name: community.general
    version: '<5.0.0'
  - name: community.libvirt
